export const ACTION_TYPES = {
    SET_SIGNUP_FIELD: "SET_SIGNUP_FIELD",

    //notes
    ADD_NOTE: "ADD_NOTE",
    LOAD_NOTES: "LOAD_NOTES",
    UPDATE_NOTE: "UPDATE_NOTE",
    CLEAR_NOTES: "CLEAR_NOTES",
    DELETE_NOTE: "DELETE_NOTE",

    //modal
    SET_MODAL_VISIBILITY: "SET_MODAL_VISIBILITY",
    SET_IS_EDIT: "SET_IS)EDIT",
    SET_CURRENT_NOTE: "SET_CURRENT_NOTE"
    

}